### ISSUE TITLE
loghi

### ISSUE THREAD

**Issue by Saraveg** [ondata/datibenecomune#1]
Non ho capito se mettiamo i loghi delle veri delle org. Se si inizio ad allegare il nostro e potete dare seguito all'issue con i vostri [

![Logo AA_Nuovo_RGB](https://user-images.githubusercontent.com/22255392/98240513-d0339280-1f69-11eb-8a30-6111576a3a04.jpg)

**Comment by aborruso** [comment]
Sì è perfetto, grazie

**Comment by susanna-sferro** [comment]
ecco i nostri pos/neg 
![TRANSPARENCY_ITALIA_01_AZZ](https://user-images.githubusercontent.com/73997205/98243453-43d79e80-1f6e-11eb-8029-2fcc3d603966.png)
![TRANSPARENCY_ITALIA_01_NEG](https://user-images.githubusercontent.com/73997205/98243509-581b9b80-1f6e-11eb-8201-cd5bb1164f0e.png)

**Comment by aborruso** [comment]
Da Davide

> solo per dirti che aderiamo anche con info.nodes un’altra associazione di cui faccio parte www.infonodes.org

**Comment by sergiocima** [comment]
![logo-01_3](https://user-images.githubusercontent.com/1728241/98346741-af754680-2016-11eb-87d9-eb6d5ac635f7.png)
Ecco Sienza in rete. Grazie!
