### ISSUE TITLE
Adesioni collettive

### ISSUE THREAD

**Issue by Saraveg** [ondata/datibenecomune#15]
si aggiunge

Fondazione OpenPolis

e

Unione degli Studenti (mi stanno mandando il logo)

@nelsonmau  @emmecola

**Comment by Saraveg** [comment]
![uds](https://user-images.githubusercontent.com/22255392/98357226-329d9900-2025-11eb-857f-ee0fff00f0dc.png)

**Comment by nelsonmau** [comment]
messi entrambi, chiudo qui. 

Per ogni nuovo partner però fai una issue singola, tnx
