### ISSUE TITLE
Problema con il link dalla petizione di change.org

### ISSUE THREAD

**Issue by ErikaMarconato** [ondata/datibenecomune#16]
Il link al sito del progetto dalla petizione ha un punto e virgola dopo la barra che risulta in 404 (probabilmente un errore in copia e incolla sull'html).
![Immagine](https://user-images.githubusercontent.com/42349179/98361018-18ff5000-202b-11eb-8b72-af53307ced94.png)

**Comment by nelsonmau** [comment]
ora funzia, grazie per il feedback!
