### ISSUE TITLE
Adesioni individuali / Aggiungere il ruolo?

### ISSUE THREAD

**Issue by nelsonmau** [ondata/datibenecomune#17]
dice @saraveg
> Facciamo qui
io ci provo e vi chiedo di segnalare errori, intanto che edito

Ettore Di Cesare, Co-Fondatore OpenPolis
Erika Marconato,
Moreno Colaiacovo, Bioinformatico
Matteo Brunati
Matteo Fortini, attivista digitale
Alberto Cottica
Isaia Invernizzi, Giornalista de Il Post
Gloria Riva, Giornalista de L’Espresso
Riccardo Saporiti, Giornalista de Il Sole 24 Ore e Wired
Luca Tremolada, Giornalista de Il Sole 24 ore
Luca Zorloni, Giornalista di Wired
Raffaele Angius, Giornalista di Wired e Agi
Gloria Lodi
Alberto Puliafito, Direttore Slow News

- [x] Erika Marconato
- [x] Moreno Colaiacovo
- [x] Matteo Brunati
- [x] Matteo Fortini
- [ ] Alberto Cottica
- [x] Isaia Invernizzi
- [x] Gloria Riva
- [x] Riccardo Saporiti
- [x] Luca Tremolada
- [x] Luca Zorloni
- [x] Raffaele Angius
- [ ] Giorgia Lodi
- [ ] Daniele Crespi
- [ ] Giuseppe Sollazzo
- [x] Alberto Puliafito
- [ ] Rosy Battaglia
- [ ] Stefano Vergine
- [x] Lisa Iotti
- [x] Marco Visconti
- [x] Irene Sicurella
- [x] Maurizio Napolitano
- [x] Valentina Bazzarin
- [x] Alice Corona
- [x] Paola Chiara Masuzzo

**Comment by dagoneye** [comment]
Erika Marconato, co-fondatrice di #CivicHackingIT 
Matteo Brunati, co-fondatore di #CivicHackingIT

**Comment by Saraveg** [comment]
Intanto ti aggiungo 
Marco Visconti, Responsabile ICT Area Nazionale Ricerca Cure Primarie del Co.S. Consorzio Sanità
![WhatsApp Image 2020-11-06 at 13 24 22](https://user-images.githubusercontent.com/22255392/98365937-78615e00-2033-11eb-8273-6aa3f719c885.jpeg)

sono d'accordo con @nelsonmau che mi fermerei qui,
Ma lui essendo medico penso sia importante e significativo

e si....dobbiamo equilibrare i generi.........

**Comment by Saraveg** [comment]
Sulla questione di metterci noi non sono d'accordo di principio (poiché io e elisa ad esempio siamo AA) ma per fare quota rosa (questo messaggio si autodistruggerà presto spero!!!) potremmo inserirci. donata, io e elisa

**Comment by emmecola** [comment]
Potete aggiungere Lisa Iotti, giornalista RAI?

Il ven 6 nov 2020, 13:21 Saraveg <notifications@github.com> ha scritto:

**Comment by emmecola** [comment]
L'ho già aggiunta io

**Comment by aborruso** [comment]
@emmecola aggiungi per favore tra le faccine Maurizio Napolitano?

**Comment by emmecola** [comment]
Ok ma non ho la foto

**Comment by aborruso** [comment]
Quella di Twitter, o quella che ti piace che trovi sul web

Grazie

______
Scusami per la brevità, ti sto scrivendo dal cellulare.

website: https://medium.com/tantotanto
38° 7' 48" N, 13° 21' 9" E EPSG:4326

Il ven 6 nov 2020, 13:51 Moreno Colaiacovo <notifications@github.com> ha
scritto:

**Comment by dontyna** [comment]
Mi vengono in mente anche Paola Masuzzo e Cristina Da Rold. 
Una volta lanciata posso chiedere anche a Roberta Villa e Beatrice Mautino.

**Comment by emmecola** [comment]
Ho aggiunto Irene Sicurella (giornalista RAI) e Maurizio Napolitano

**Comment by nelsonmau** [comment]
grazie @emmecola !

**Comment by Saraveg** [comment]
Si aggiunge Valentina Bazzarin, ricercatrice
![Bazzarin](https://user-images.githubusercontent.com/22255392/98374627-3ccd9080-2041-11eb-8725-801d1af4cc77.jpeg)

**Comment by dontyna** [comment]
Paola Chiara Masuzzo, scienzata dei dati e attivista open science

**Comment by nelsonmau** [comment]
@emmecola puoi occuparti tu di aggiungerle? ti assegno la issue come se fosse un task
In caso contrario dimmi se non ce la fai e riassegna a me

grazie!

**Comment by dontyna** [comment]
Alice Corona, comunicazione dati & data activism

**Comment by emmecola** [comment]
Ok @nelsonmau lo faccio.. Mandatemi delle foto se le avete, altrimenti cerco io su internet

**Comment by nelsonmau** [comment]
Adesioni inserite e descrizioni aggiornate, chiudo issue

tnx a tout le monde
