### ISSUE TITLE
Adesione Priorità alla scuola

### ISSUE THREAD

**Issue by Saraveg** [ondata/datibenecomune#18]
Aderisce la rete Priorità alla Scuola
<img width="295" alt="PaS" src="https://user-images.githubusercontent.com/22255392/98362303-4d740b80-202d-11eb-9a8c-5cfce7eae539.png">

(ma che elenco incredibilmente variegato!! bello!)

**Comment by Saraveg** [comment]
Magari questo logo è più decente?
![#PrimaLaScuola_Paulesu](https://user-images.githubusercontent.com/22255392/98362984-8496ec80-202e-11eb-880b-782e28f64d07.jpg)

**Comment by Saraveg** [comment]
Dopodiché apro un issue per rifargli il logo, porelli. Ma so forti eh, se lo meriterebbero!

**Comment by nelsonmau** [comment]
ma se gli mettiamo questo che almeno si legge? e poi che sito mettiamo? la pagina facebook?

![Uploading 119201935_173345631055902_3219583126265600579_o.png…]()

**Comment by Saraveg** [comment]
si ad ambedue le domande

**Comment by Saraveg** [comment]
Continuo a mettere qui
Hanno aderito anche Link e Rete della Conoscenza
Abbiamo tutto il panorama delle organizzazioni di studenti (anche primarie con priorità alla scuola)
Vi giuro che noi abbiamo solo fatto una telefonata ma l'entusiasmo è schizzato alle stelle!

Che faccio recupero i loghi?

**Comment by nelsonmau** [comment]
yes grazie

**Comment by Saraveg** [comment]
![Uploading Link_-_Coordinamento_Universitario.png…]()

**Comment by Saraveg** [comment]
![rete](https://user-images.githubusercontent.com/22255392/98369246-ec523500-2038-11eb-87a6-ef1023c68e01.png)

**Comment by Saraveg** [comment]
![Link_-_Coordinamento_Universitario](https://user-images.githubusercontent.com/22255392/98369303-0a1f9a00-2039-11eb-9463-7f9f776519a9.png)

**Comment by nelsonmau** [comment]
fatto, grazie, chiudo qui
