### ISSUE TITLE
Condivisione Twitter

### ISSUE THREAD

**Issue by Saraveg** [ondata/datibenecomune#19]
Sbaglio o è sparita la condivisione twitter da sito?

**Comment by dontyna** [comment]
L'ha tolta @nelsonmau ma siamo per rimetterla.

**Comment by nelsonmau** [comment]
@Saraveg beh, io avevo proposto di toglierla, non l'avevo proprio tolta :-) 
Il senso è semplice e riguarda il flusso di navigazione che fa l'utente:

1. l'utente intercetta la campagna
2. l'utente clicca su "firma la petizione"
3. l'utente va su change
4. dopo la firma, già da change più condividere la campagna. 

Avere un pulsante "twitta" sul sito datibenecomune.it non è quindi utilissimo secondo me, anzi forse dispersivo. 
ma sono i miei due cents :-)

**Comment by dontyna** [comment]
È che non è detto che le persone firmino la petizione, volevamo comunque fare azioni di tweetstorm.

**Comment by dontyna** [comment]
@nelsonmau se si può rimettere attivo :) grazie

**Comment by nelsonmau** [comment]
fatto, check please
