### ISSUE TITLE
Documento per mappatura adesioni

### ISSUE THREAD

**Issue by nelsonmau** [ondata/datibenecomune#20]
@saraveg occorre avere un documento dove mappare tutte le adesioni, perché potrebbero esserci discrepanze tra quelle del sito e quelle reali. L'ho assegno a te, ma lo convidivo anche via mail

**Comment by Saraveg** [comment]
vado, con le mail.

**Comment by Saraveg** [comment]
https://docs.google.com/document/d/1rPyxyOIOw7ekLAeFaL5WKZ9neSF4dM_2mdS4_2btHMA/edit

Questo è estrapolato dal cs + le ultime che ho visto (biotecnologi)

La suddivisione mi convince.

Ma come organizziamo le prossime?

**Comment by nelsonmau** [comment]
direi che per adesioni di nuove organizzazioni ce lo comunichiamo via mail come fatto fin qui

per le adesioni di singole persone "bloccherei" per il momento, a meno che non si tratti di super-adesioni che so tipo Madonna o Bono degli U2. 

Condivido lo spreadsheet nel thread mail

grazie mille
