### ISSUE TITLE
link petizione top menu

### ISSUE THREAD

**Issue by susanna-sferro** [ondata/datibenecomune#21]
non va da nessuna parte. linkiamo direttamente su change?

**Comment by nelsonmau** [comment]
hai ragione... in teoria dovrebbe andare nel pulsante in basso, ma siccome poi l'ho messo fisso, non ha senso il doppio link. 

@dontyna @saraveg che dite voi?

**Comment by Saraveg** [comment]
Io penso che o si linka o si toglie 

sarei per linkarlo
