### ISSUE TITLE
testo petizione change

### ISSUE THREAD

**Issue by Saraveg** [ondata/datibenecomune#25]
è rimasto quello vecchissimo

dobbiamo coordinarlo

chi puo'?
solo @dontyna?

**Comment by nelsonmau** [comment]
lo fa @dontyna e appena fatto, chiude la issue qui. 

@Saraveg ci linki qui il testo finale please?
grazie

**Comment by Saraveg** [comment]
Per me da ora in poi vale il testo sul sito


Viviamo una grave crisi. La società civile italiana, una delle più mature e competenti del mondo, è pronta a supportare le istituzioni nel farvi fronte.

Per farlo, però, ha bisogno di dati. La cittadinanza, stremata, chiede risposte mirate, meno gravose di "tutti in lockdown". Elaborarle richiede dati pubblici, disaggregati, continuamente aggiornati, ben documentati e facilmente accessibili a ricercatori, decisori, media e cittadini. Il nuovo sistema di classificazione del territorio nazionale in tre aree di rischio rappresenta, in questo senso, un'opportunità, perché comporta un sofisticato sistema di monitoraggio nazionale e quindi genererà, si presume, molti dati di qualità.

Il governo è consapevole di tutto questo. Un recente documento di indirizzo pone "la trasparenza e l'accessibilità dei dati al centro della strategia di gestione del rischio pandemico". Pandemia a parte, l'Italia si impegna da tempo per la trasparenza amministrativa. In sede internazionale, per esempio, siede nel board dell'Open Government Partnership. Purtroppo, adottare un indirizzo non è sufficiente: bisogna anche tradurlo in pratica. E questo significa lavoro duro: misure attuative, integrazione di flussi informativi, data stores. Come sempre, la differenza tra il dire e il fare è... il fare.

Per questo, chiediamo al Governo Italiano di:

rendere disponibili, aperti e interoperabili (machine readable) e non aggregati, tutti i dati comunicati dalle Regioni al Governo dall'inizio dell'epidemia per monitorare e classificare il rischio epidemico (compresi tutti gli indicatori di processo sulla capacità di monitoraggio e di accertamento e quelli di risultato) e fare lo stesso per tutti i dati che alimentano i bollettini con il dettaglio regionale, provinciale e comunale, della cosiddetta Sorveglianza integrata COVID-19 dell'Istituto Superiore di Sanità, così come i dati relativi ai contagi all’interno dei sistemi, in particolar modo scolastici. Tutti i dati dovrebbero essere completati dalla data di trasmissione e aggiornamento;

rendere pubbliche le evidenze scientifiche che mettono in correlazione la valutazione del rischio, le misure restrittive e l’impatto epidemiologico ad esso correlato;

recepire nella gestione, pubblicazione e descrizione dei dati tutte le raccomandazioni della task force “Gruppo di lavoro 2 – Data collection and Infrastructure“, presenti nel documento “Analisi dei flussi e mappatura delle banche dati di interesse per la task force dati per l’emergenza COVID-19”;

nominare un/a referente COVID-19 su dati e trasparenza e un/a referente per ogni regione, a cui la società civile possa fare riferimento;

istituire un centro nazionale, in rete con omologhi centri regionali, dedicato ai dati Covid, che non solo imponga standard e formati, ma che coordini e integri nuovi sistemi di raccolta e individui le criticità in quelli esistenti.

Vediamo di continuo decisioni prese per limitare il contagio sulla base di dati che non sono pubblici: la trasparenza è alla base di ogni democrazia! I cittadini hanno il diritto di conoscere su quali dati e quali analisi si basano le decisioni prese dal governo per le restrizioni dei prossimi DPCM. Da questi dati dipende la nostra vita quotidiana, il nostro lavoro, la nostra salute mentale: vogliamo che siano pubblici! E vogliamo che siano in formato aperto, perché dobbiamo permettere agli scienziati e ai giornalisti di lavorare per bene.

I firmatari di questa lettera sono estremamente preoccupati per il crollo di fiducia generato dalla gestione dell’emergenza COVID-19. In questo momento una corretta comunicazione, basata sull’evidenza dei dati, è quanto mai importante per comprendere le scelte istituzionali che hanno profonde conseguenze sulla vita delle persone.

**Comment by Saraveg** [comment]
Ho creato questo gdoc che può sostituire il precedente

https://docs.google.com/document/d/1BswLZwfq9BmuGWlxRA8mkyhuVxgSVK_kVVrMerDbcbM/edit#

**Comment by dontyna** [comment]
Ho modificato, fate un check e poi chiudete pure issue.

**Comment by Saraveg** [comment]
a me torna tutto grazie!!

**Comment by Saraveg** [comment]
@dontyna sto fusa...in realtà non è stessa versione....

**Comment by nelsonmau** [comment]
@Saraveg occorre fare nuove modifiche o possiamo chiudere la issue?
grazie

**Comment by nelsonmau** [comment]
ho adeguato il testo della petizione su change a quello del sito datibenecomune.it
per cui per me la issue è chiusa. 
Eventuali nuove modifiche devono essere fatte prima su un testo master (il gdoc) e poi riportate sia sul sito che su change. 

chiudo la issue
