### ISSUE TITLE
Maggior dettaglio lato formule/algoritmi

### ISSUE THREAD

**Issue by mfortini** [ondata/datibenecomune#28]
Se possibile, amplierei la frase
"rendere pubbliche le evidenze scientifiche che mettono in correlazione la valutazione del rischio, le misure restrittive e l’impatto epidemiologico ad esso correlato;"

Facendola diventare rendere "pubbliche le evidenze scientifiche, le formule e gli algoritmi"

Per la sintesi datibenecomune come slogan va bene, ma siamo in una situazione nuova: non più soltanto attivist* e giornalist* che vogliono monitorare e analizzare dati, ma cittadin* e imprese la cui vita è impattata pesantemente  da formule e algoritmi che bisogna poter verificare.

La verifica si fa sempre nello stesso modo: dati gli input, devo poter applicare la formula e l'algoritmo e poter ottenere lo stesso output

**Comment by nelsonmau** [comment]
ciao @mfortini, ok per la modifica frase, mi pare cosa giusta. 

faccio solo un giro interno con gli altri per sentire anche da loro.

**Comment by nelsonmau** [comment]
@saraveg, io integrerei questo suggerimento di Matteo, mi pare pertinente e giustissimo?

**Comment by aborruso** [comment]
Per me ottimo. Grazie @mfortini

**Comment by Saraveg** [comment]
anche per me!
