### ISSUE TITLE
Modificare la card per social inserendo "COVID-19"

### ISSUE THREAD

**Issue by nelsonmau** [ondata/datibenecomune#29]
@aborruso la card per social, che al momento è come allego da screenshot, va modificata adeguando il testo in modo che si capisca subito che vogliamo i dati sul covid-19. 

Adesso il testo è:
- Dati aperti, ben descritti, aggiornati e machine readable

Puoi invece mettere please:
- Vogliamo dati aperti sul COVID-19, ben descritti, aggiornati e machine readable

Se lo fai asap TVTB (ma anche @saraveg imho)

tnx

**Comment by aborruso** [comment]
Eccola https://github.com/ondata/datibenecomune/blob/main/share/twitterVisual.png

**Comment by nelsonmau** [comment]
@aborruso ho inserito questa nuova card nella petizione su change.org. 

Tu dove l'hai inserita?

**Comment by nelsonmau** [comment]
Ora è corretta su:
1) change.org
2) facebook
3) twitter

chiudo la issue
