### ISSUE TITLE
Parentesi di troppo

### ISSUE THREAD

**Issue by emmecola** [ondata/datibenecomune#3]
In fondo al secondo paragrafo c'è una parentesi di troppo..

**Comment by aborruso** [comment]
Ti ho invitato nel repo, correggila tu per favore ;)

**Comment by aborruso** [comment]
@emmecola ma come, cambi il codice e non chiudi issue??

Se per te è ok, please chiudila

**Comment by aborruso** [comment]
Lo faccio :)
