### ISSUE TITLE
Raccogliamo qui notizie correlate

### ISSUE THREAD

**Issue by aborruso** [ondata/datibenecomune#31]
> *   **Pubblicazione dei risultati del monitoraggio dei dati epidemiologici**
> 
> Sono rafforzati gli obblighi di pubblicità e trasparenza in relazione al monitoraggio e all’elaborazione dei dati epidemiologici rilevanti per la classificazione delle aree del paese destinatarie delle varie misure di contenimento, già individuate, fra quelle previste dalla normativa primaria, con decreto del Presidente del Consiglio dei ministri del 3 novembre 2020.

Source: [Comunicato stampa del Consiglio dei Ministri n. 72](http://www.governo.it/it/articolo/comunicato-stampa-del-consiglio-dei-ministri-n-72/15643)

**Comment by dagoneye** [comment]
Non so se valga la pena distinguerli, ma ci sono sicuramente due filoni su cui prestare attenzione: 
1. dati e informazioni che avevamo nel momento di questo appello che stanno avendo problemi di pubblicazione e/o sparendo (ritardi, si spesa, ma è esattamente il contrario di quello che si vorrebbe dalle istituzioni - penso a [questo tweet](https://twitter.com/Ruffino_Lorenzo/status/1325521907572224002);
2. dati e informazioni che sono parte di quello che stiamo chiedendo e sono nascosti tra le maglie della complessità, come il link alla famosa piattaforma del'ISS [citato in questo tweet](https://twitter.com/emmecola/status/1325004105832599555) ovvero https://covid-19.iss.it

Potremmo segnalarne un po' qui e capire bottom-up di cosa si tratta per valutare poi come gestirle o mostrarle nel sito.

**Comment by emmecola** [comment]
Riporto qui la segnalazione di @dontyna 

https://mailchi.mp/2ee7214409d2/koselig-4804330?e=09449333c7

**Comment by nelsonmau** [comment]
@emmecola @dagoneye @aborruso vi avviso, ma lo sapete già: queste discussioni possono convergere sui vari canarli Slack, chiudo la issue quindi! tnx
