### ISSUE TITLE
URL petizione Change

### ISSUE THREAD

**Issue by emmecola** [ondata/datibenecomune#33]
Mi hanno fatto notare che l'URL della petizione su Change sembra un attacco personale a Conte, secondo voi si può modificare?

https://www.change.org/p/giuseppe-conte-dove-sono-i-dati

Effettivamente dire "Giuseppe Conte, dove sono i dati?" può sembrare una presa di posizione politica, magari qualche associazione firmataria preferirebbe un tono più soft.

Moreno

**Comment by nelsonmau** [comment]
esattamente dov'è presente questo url? io in giro vero questo
https://www.change.org/p/datibenecomune-in-formato-aperto-ben-descritti-e-machine-readable-palazzo-chigi-giuseppeconteit-datibenecomune-giuseppeconteit

**Comment by emmecola** [comment]
Se clicchi "Firma adesso la petizione" in fondo a datibenecomune.it, il link rimanda all'URL che ti ho scritto sopra.. Non so come funzioni Change, ma pare ci siano due URL con la stessa petizione..

**Comment by nelsonmau** [comment]
io vedo questo https://www.change.org/datibenecomune
se controlli nel DOM vedrai che c'è questo ...

forse gli url sono tre... sarà uno shortner, ma anche da backend non lo vedo modificabile...

**Comment by nelsonmau** [comment]
direi che la issue è chiusa :-)
