### ISSUE TITLE
Donazioni su change

### ISSUE THREAD

**Issue by Saraveg** [ondata/datibenecomune#34]
Abbiamo poi visto se c'è modo di toglierle?
mi sono arrivate diverse segnalazioni e le persone stanno donando....

che ne pensate?

**Comment by nelsonmau** [comment]
non si possono togliere, ma possiamo aggiungere disclaimer tipo: 
> Per promuovere questa petizione puoi fare una donazione facoltative. Attenzione: queste donazioni vanno direttamente a Change.org, i promotori della petizione non ricevono in alcun modo denaro derivante da esse. [Maggiori info qui](https://help.change.org/s/article/Promoted-Petitions-FAQs?language=it)

**Comment by aborruso** [comment]
Credo che vadano a change.org per fare "girare" meglio e di più la
petizione.

Se è così modificherei in   "Attenzione: queste donazioni vanno
direttamente a Change.org, per ottimizzare la promozione di questa
petizione. I promotori della petizione non ricevono in alcun modo denaro
derivante da esse. Maggiori info qui"

**Comment by nelsonmau** [comment]
@Saraveg se sei d'accordo, mettiamo quest'ultima versione proposta da @aborruso

**Comment by aborruso** [comment]
@nelsonmau ok, lo faccio.

Non ho mai usato change da admin: mi sembra di poterlo inserire soltanto nel testo della petizione. Nelson mi confermi?

**Comment by nelsonmau** [comment]
Sì nel testo, considera che puoi mettere un po' di formattazione

**Comment by aborruso** [comment]
Ho aggiunto un "nota bene" alla fine
