### ISSUE TITLE
problemi visualizzazione sito

### ISSUE THREAD

**Issue by susanna-sferro** [ondata/datibenecomune#35]
stamattina lo vedo così

![image](https://user-images.githubusercontent.com/73997205/98517847-dcbc3180-226e-11eb-8328-98a688d11349.png)

**Comment by nelsonmau** [comment]
@susanna-sferro puoi dirci con che browser e che risoluzione?

**Comment by emmecola** [comment]
Credo sia perché il titolo è diventato troppo lungo adesso.. Che faccio, rimpicciolisco il tag h1 nel CSS? @nelsonmau @aborruso

**Comment by emmecola** [comment]
> @susanna-sferro puoi dirci con che browser e che risoluzione?

Vedo lo stesso difetto con Chrome, Firefox e Edge

Risoluzione 1920 x 1080, impostazione Windows "Dimensioni testo, app e altri elementi" settata a 150% (scelta consigliata)

**Comment by nelsonmau** [comment]
ok @emmecola, magari puoi metterlo `rem` così è proporziale... è un po' scocciante perché vanno fatti vari test, ma se hai tempo di farli, ottimo!

**Comment by susanna-sferro** [comment]
io lo vedo cosi con chrome ris 1920x1080

**Comment by emmecola** [comment]
> ok @emmecola, magari puoi metterlo `rem` così è proporziale... è un po' scocciante perché vanno fatti vari test, ma se hai tempo di farli, ottimo!

Ho provato a modificare un po' il CSS @nelsonmau , ma forse non l'ho capito bene perché le modifiche non hanno effetto. Scusami, lo sviluppo web non è il mio mestiere, mi sa che ti tocca farlo tu :-)

MI CORREGGO.. Funziona, dovevo solo fare un refresh :-D

**Comment by nelsonmau** [comment]
@susanna-sferro puoi verificare adesso? 
se vedi lo stesso problema please ctrl+f5

**Comment by susanna-sferro** [comment]
perfetto cosi!

**Comment by nelsonmau** [comment]
:champagne: per @emmecola :-)
