### ISSUE TITLE
nuova adesione - Simone Cosimi

### ISSUE THREAD

**Issue by susanna-sferro** [ondata/datibenecomune#36]
Simone Cosimi 
giornalista freelance

![simone_cosimi](https://user-images.githubusercontent.com/73997205/98519586-3b82aa80-2271-11eb-92e9-fea36c1dc410.jpg)

**Comment by emmecola** [comment]
Non so se possiamo inserire altre adesioni di singoli adesso.. Non rischiamo di avere troppe foto da aggiungere? @aborruso @nelsonmau

**Comment by nelsonmau** [comment]
grazie @emmecola e @susanna-sferro, sulle adesioni personali ho proposto di tenerle un attimo in standy, perché il luogo ideale per farlo è firmare la petizione. 

Teniamolo per il momento in sospeso, tnx

**Comment by aborruso** [comment]
Ciao per il momento le adesioni singole le abbiamo fermate (ieri ne è stata aggiunta una, per una dimenticanza mia e di @dontyna , era uno dei primi 5 singoli)

Qui la chiudo.

Nei prossimi giorni però dovremmo trovare il modo di raccoglierle comunque e coinvolgere i singoli aderenti
