### ISSUE TITLE
Partiti politici

### ISSUE THREAD

**Issue by emmecola** [ondata/datibenecomune#39]
Ciao, non so se questo punto sia mai stato discusso.. Non credo.

Mi ha scritto Giordano Masini, vorrebbe aggiungere Più Europa tra le organizzazioni che sostengono la campagna. Ha già inviato la richiesta tramite l'apposito link sul sito. Cosa ne pensate? Aggiungere un partito politico, per quanto piccolo, può darci un vantaggio di visibilità (mi ha detto che farebbero un post pubblico nel pomeriggio, nel caso). D'altra parte, si rischia di politicizzare la campagna..

Fatemi sapere!

Moreno

**Comment by marcomosti** [comment]
A nostro avviso e per nostra policy Fondazone GIMBE meglio non avere partiti come promotori

**Comment by nelsonmau** [comment]
@marcomosti grazie per il feedback. Considera che abbiamo spostato tutte le discussioni su uno spazio Slack dedicato alla campagna. Ti hanno già girato il link per entrare? Sennò ti guido io volentieri, eventualmente scrivimi su nelson@ondata.it e ti do le info
grazie!
