### ISSUE TITLE
Lista promotori

### ISSUE THREAD

**Issue by aborruso** [ondata/datibenecomune#4]
Inserire:

- [ ] ActionAid
- [ ] Transparency
- [ ] onData
- [ ] Scienza in rete
- [ ] Ettore di Cesare
- [ ] Alberto Cottica
- [ ] Moreno Colaiacovo
- [ ] Erika Marconato
- [ ] Matteo Brunati

**Comment by dagoneye** [comment]
Occhio: Erika (e non Erica)

**Comment by aborruso** [comment]
> Occhio: Erika (e non Erica)

Mi devo drogare di meno. Grazie
