### ISSUE TITLE
Dimensione foto header

### ISSUE THREAD

**Issue by pdottor** [ondata/datibenecomune#41]
Mi servirebbe avere le specifiche (px) in modo da finalizzare l'immagine con il grafico. L'immagine di sfondo dev'essere senza scritte immagino, visto che poi il titolo e sottotitolo saranno inseriti separatamente.

**Comment by nelsonmau** [comment]
la proporzione è 1930x1000

**Comment by nelsonmau** [comment]
fatto qui, abbiamo risolto in #46
