### ISSUE TITLE
Numero firmatari della petizione da mettere sul sito

### ISSUE THREAD

**Issue by nelsonmau** [ondata/datibenecomune#43]
ciao, questa è per @aborruso e @jenkin 
come sapete change non ha delle API

vedo però nella [pagina della petizione](https://www.change.org/p/datibenecomune-in-formato-aperto-ben-descritti-e-machine-readable-palazzo-chigi-giuseppeconteit) che sotto il cofano ci sono parecchi dati che in teoria possiamo estrarre (anche i firmatari giornalieri). Mi riferisco in particolare a [questo json](https://www.change.org/api-proxy/-/petitions/25684771/updates/recent?t=14728280-269a-11eb-8dd5-ef06d5398493) che è accessibile anche da utente anonimo. 

Il conteggio dei firmatari si trova in particolare in un item del json, in questa chiave `[0].petition.total_signature_count`

Valutare su tirare già anche altri dati

**Comment by jenkin** [comment]
La rappresentazione della petizione con tutti i dati che ci servono è all'url https://www.change.org/api-proxy/-/petitions/25684771. 

Ma naturalmente lato Change non sono abilitati i [CORS](https://developer.mozilla.org/it/docs/Web/HTTP/CORS), per cui non è possibile far fare al browser dell'utente che visita `datibenecomune.it` una chiamata a `change.org`.

L'unica soluzione è usare il server di ondata per impostare un proxy. Non abbiamo grande traffico sul nostro sito, ma certo non è il massimo della cortesia nei confronti di Change, ci vorrebbe una soluzione più raffinata con una cache ([esempio](https://taylor.callsen.me/creating-a-caching-proxy-server-with-apache/)).

**Comment by aborruso** [comment]
@jenkin per il momento ho attivato un download ogni due ore qui https://raw.githubusercontent.com/ondata/datibenecomune/main/risorse/firmatariChange

Tramite questo https://github.com/ondata/datibenecomune/blob/main/script/datiChange.sh

**Comment by jenkin** [comment]
Ah beh, così è facile! Non serve il file `firmatariChange`, mi vado a prendere direttamente il json `datiChange.json`.

Che ne dite? :D

![Screenshot_20201119_114211](https://user-images.githubusercontent.com/426495/99655792-6c769280-2a5c-11eb-840b-f49cd28f72e2.png)

**Comment by jenkin** [comment]
O anche meglio...

![Screenshot_20201119_114634](https://user-images.githubusercontent.com/426495/99656214-e9097100-2a5c-11eb-9524-1d3b4c38654d.png)

**Comment by aborruso** [comment]
> Ah beh, così è facile! Non serve il file `firmatariChange`, mi vado a prendere direttamente il json `datiChange.json`.

Ci mancherebbe, e prendo pure [quello](https://github.com/ondata/datibenecomune/blob/main/risorse/datiChange.json) e l'archivio. E lo so che è facile.
Se vuoi, è lì.

Mi piace il secondo

**Comment by jenkin** [comment]
![Screenshot_20201119_115324](https://user-images.githubusercontent.com/426495/99656981-d80d2f80-2a5d-11eb-8bf3-93a58f5982e5.png)

**Comment by nelsonmau** [comment]
ho riaperto la issue perché dal punto di vista grafico è una soluzione che non mi piace affatto. 

Il dato delle firme va valorizzato al massimo, non messo in basso a destra in piccolo. 

Per me intanto si può fare come da screenshot

![2020 11 19-datibenecomune it](https://user-images.githubusercontent.com/1769578/99669677-ba48c600-2a6f-11eb-9307-f261550ab42d.png)

**Comment by jenkin** [comment]
Coinvolgiamo il grafico... :)

**Comment by nelsonmau** [comment]
@jenkin ho parlato con il grafico del sito (che sono io) e dire che ha trovato un'ottima soluzione, allego screenshot. 

grazie mille a te ed @aborruso e a presto! ;-)


![2020 11 22-localhost_8000](https://user-images.githubusercontent.com/1769578/99897881-923eaa00-2c9d-11eb-803b-fb43791da931.png)
