### ISSUE TITLE
Licenza dei contenuti da esplicitare nel footer

### ISSUE THREAD

**Issue by dagoneye** [ondata/datibenecomune#7]
È meglio inserire anche una licenza del contenuto: quale mettiamo? 

1. [CC0](https://creativecommons.org/publicdomain/zero/1.0/deed.it) -  ? 
2. [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.it)? 

Pensiamo anche ai giornalisti che potrebbero citare l'iniziativa, così li facilitiamo. 
Occhio all'immagine che fa da sfondo e i loghi delle singole associazioni.

**Comment by aborruso** [comment]
Direi CC BY 4.0. Per il momento la metto

**Comment by aborruso** [comment]
Inserito anche riferimento ad autore foto.

Grazie
