### ISSUE TITLE
Definire testo del tweet

### ISSUE THREAD

**Issue by aborruso** [ondata/datibenecomune#8]
@dontyna per favore mi scrivi o confermi il testo del tweet?

Per ora è

> #datiBeneComune Voglio tutti i dati comunicati dalle Regioni al Governo per monitorare e classificare il rischio epidemico, in formato aperto, ben descritti e machine readable @Palazzo_Chigi
https://datibenecomune.it/ 

![image](https://user-images.githubusercontent.com/30607/98298693-afddf500-1fb6-11eb-86e7-07e877836b48.png)

**Comment by dontyna** [comment]
#datiBeneComune Voglio tutti i dati comunicati dalle Regioni al Governo per monitorare e classificare il rischio epidemico, in formato aperto, ben descritti e machine readable @Palazzo_Chigi @GiuseppeConteIT
https://datibenecomune.it/

@nelsonmau
