### ISSUE TITLE
Tre nuove adesioni individuali

### ISSUE THREAD

**Issue by Saraveg** [ondata/datibenecomune#9]
avevamo detto di specificare il ruolo di ognuno che così non è che si capisce il "valore" delle adesioni individuali.
ho visto che sono linkabili ma dove vanno?

**Comment by aborruso** [comment]
Ciao @Saraveg 
da alcuni minuti non sono più linkabili (fai reload).

Io avevo chiesto ieri di inserire la qualifica accanto a ogni nome, ma probabilmente la cosa è sfuggita.
Ieri ho fatto le 00;30, per tutti i loghi mancanti, per le fotine, per la formattazione.
Per questo chiedevo una mano.

Se si predispone nel documento condiviso (o altro) per ogni nome, la qualifica accanto, @nelsonmau penso che le possa inserire

**Comment by Saraveg** [comment]
Facciamo qui? @nelsonmau 
io ci provo e vi chiedo di segnalare errori, intanto che edito

Ettore Di Cesare, Co-Fondatore OpenPolis 
Erika Marconato,
Moreno Colaiacovo, Bioinformatico
Matteo Brunati
Matteo Fortini, attivista digitale
Alberto Cottica
Isaia Invernizzi, Giornalista de Il Post
Gloria Riva, Giornalista de L’Espresso
Riccardo Saporiti,  Giornalista de Il Sole 24 Ore e Wired
Luca Tremolada, Giornalista de Il Sole 24 ore
Luca Zorloni, Giornalista di Wired
Raffaele Angius, Giornalista di Wired e Agi
Gloria Lodi
Alberto Puliafito, Direttore Slow News

**Comment by susanna-sferro** [comment]
io ho iniziato a inserire alcuni nel doc google

**Comment by Saraveg** [comment]
Fotina di Alberto Puliafito
![Alberto Puliafito](https://user-images.githubusercontent.com/22255392/98347587-e0a24680-2017-11eb-81c2-3e0519884db0.jpg)

**Comment by emmecola** [comment]
Io sono bioinformatico, l'ho aggiunto al doc Google

**Comment by susanna-sferro** [comment]
stefano vergine 
![stefano_vergine](https://user-images.githubusercontent.com/73997205/98355644-b609bb00-2022-11eb-946d-3c4d969c8c66.jpeg)

**Comment by susanna-sferro** [comment]
rosy battaglia
![Rosy_Battaglia_500](https://user-images.githubusercontent.com/73997205/98355958-2b758b80-2023-11eb-918c-e4f411feeadd.jpg)

**Comment by nelsonmau** [comment]
ho aggiunto le tre foto, sul discorso delle descrizioni dei singoli apro nuova issue
